name: Deploy to Beta Environment
'on':
  push:
    branches:
      - main
jobs:
  Beta-Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Build Steps                                                   
      run: |
        npm install
        npm run build
        
    - name: AWS Deployment
      uses: reggionick/s3-deploy@v3
      with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: us-east-1
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
    - name: Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: test-bot
        payload: |
          {
            "text": "New Beta Version Deployed",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "chatbot-dashbord - [ Beta Environment ]",
                  "emoji": true
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Author:*"
                  },
                  {
                    "type": "image",
                    "image_url": "https://github.com/${{ github.actor }}.png",
                    "alt_text": "Author-profile-pic"
                  },
                  {
                    "type": "plain_text",
                    "text":" ${{ github.actor }} "
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Ref:*\n ${{ github.ref }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event:*\n${{ github.event_name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Action URL:*\n <${{ github.event.head_commit.url }}\/checks| ${{ github.workflow }} >"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<${{ github.event.head_commit.url }}| ${{ steps.vars.outputs.sha8 }} >"
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Site URL :*<https://chatbot-dashbord.web.app|Beta Site>"
                }
              }
            ]
          }
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
