name: Deploy to Beta Environment
'on':
  push:
    branches:
      - main
jobs:
  Beta-Deployment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Build Steps                                                   
      run: |
        npm install
        npm run build
        
    - name: AWS Deployment
      uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
        
    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: "/index.html"
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: test-bot
        payload: |
          {
            "text": "New Beta Version Deployed",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "chatbot-dashbord - [ Beta Environment ]",
                  "emoji": true
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Author:*"
                  },
                  {
                    "type": "image",
                    "image_url": "https://github.com/${{ github.actor }}.png",
                    "alt_text": "Author-profile-pic"
                  },
                  {
                    "type": "plain_text",
                    "text":" ${{ github.actor }} "
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Ref:*\n ${{ github.ref }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event:*\n${{ github.event_name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Action URL:*\n <${{ github.event.head_commit.url }}\/checks| ${{ github.workflow }} >"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<${{ github.event.head_commit.url }}| ${{ steps.vars.outputs.sha8 }} >"
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Site URL :*<https://chatbot-dashbord.web.app|Beta Site>"
                }
              }
            ]
          }
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
