name: Deploy to Beta Environment
'on':
  push:
    branches:
      - main
jobs:
  Beta-Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Build Steps                                                   
      run: |
        npm install
        npm run build
        CI=false npm run build
        
    - name: AWS Deployment
      uses: reggionick/s3-deploy@v3
      with:
          folder: build
          bucket: cloudfrontdemobucket2
          bucket-region: US East (N. Virginia) us-east-1
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: b2/*
